spring:
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:postgresql://localhost:5432/dealers
    username: sa
    password:
    driverClassName: org.postgresql.Driver
