spring:
  jpa:
    show-sql: true
    database: postgresql
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:postgresql://localhost:5432/Dealer
    username: sa
    password:
    driverClassName: org.postgresql.Driver
