spring:
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  
  datasource:
    url: jdbc:postgresql://localhost:5432/dealers
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
